# Generated by Django 4.0.3 on 2022-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintData',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='roadImage')),
                ('latlong', models.CharField(max_length=50)),
            ],
        ),
    ]
