# Generated by Django 4.0.3 on 2022-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_complaintdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdata',
            name='id',
            field=models.CharField(default='14778', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaintdata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
