# Generated by Django 4.0.3 on 2022-11-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_complaintdatalocation_complaintdatamanual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdatalocation',
            name='id',
            field=models.CharField(default='17021', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaintdatamanual',
            name='id',
            field=models.CharField(default='1F6B7', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
