# Generated by Django 4.0.3 on 2022-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_complaintdatalocation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdatalocation',
            name='status',
            field=models.CharField(default=25, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintdatamanual',
            name='status',
            field=models.CharField(default=25, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintdatalocation',
            name='id',
            field=models.CharField(default='62789', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaintdatamanual',
            name='id',
            field=models.CharField(default='590ED', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
